import React, { useEffect, useState } from 'react';
import { Box, Typography, Table, TableBody, TableCell, TableHead, TableRow, Chip, Button, Dialog, DialogTitle, DialogContent, DialogActions, Divider, Alert } from '@mui/material';
import { FileText } from 'lucide-react';
import { DashboardLayout } from '../../components/layout/DashboardLayout';
import { GlassCard } from '../../components/common/GlassCard';
import { ridesApi } from '../../services/api';

export const TripHistory = () => {
  const [trips, setTrips] = useState([]); const [selected, setSelected] = useState(null); const [error, setError] = useState('');
  useEffect(() => { ridesApi.getMyRides().then((d) => setTrips(d.rides || [])).catch((e) => setError(e.response?.data?.detail || 'Unable to load rides.')); }, []);
  return <DashboardLayout title="Trip History & Receipts"><GlassCard sx={{ p: 3 }}><Typography variant="h6" sx={{ fontWeight: 800, mb: 3 }}>Past Rides & Receipts</Typography>{error && <Alert severity="error">{error}</Alert>}<Table><TableHead><TableRow>{['Trip ID','Date & Time','Route Summary','Status','Fare','Action'].map((h) => <TableCell key={h} sx={{ fontWeight: 700 }}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{trips.map((t) => <TableRow key={t.id}><TableCell sx={{ color: '#00D4FF' }}>{t.id}</TableCell><TableCell>{t.request_time ? new Date(t.request_time).toLocaleString() : '—'}</TableCell><TableCell><Typography variant="body2">{t.pickup_label || 'Pickup coordinates'}</Typography><Typography variant="caption">→ {t.destination_label || 'Destination coordinates'}</Typography></TableCell><TableCell><Chip label={t.status} size="small" /></TableCell><TableCell>₹{t.ride_option_price ?? '—'}</TableCell><TableCell><Button size="small" startIcon={<FileText size={14} />} onClick={() => setSelected(t)}>Receipt</Button></TableCell></TableRow>)}</TableBody></Table>{!trips.length && !error && <Typography color="text.secondary" sx={{ mt: 2 }}>No rides found.</Typography>}</GlassCard><Dialog open={Boolean(selected)} onClose={() => setSelected(null)}><DialogTitle>SmartRoute AI Receipt</DialogTitle><DialogContent>{selected && <Box><Typography variant="caption">#{selected.id}</Typography><Divider sx={{ my: 2 }} /><Typography>Pickup: {selected.pickup_label || 'Coordinates'}</Typography><Typography>Destination: {selected.destination_label || 'Coordinates'}</Typography><Typography sx={{ mt: 2 }}>Fare: ₹{selected.ride_option_price ?? '—'}</Typography></Box>}</DialogContent><DialogActions><Button onClick={() => setSelected(null)}>Close</Button></DialogActions></Dialog></DashboardLayout>;
};
