// Sample data for SmartRoute AI fallback & demonstration mode

export const MOCK_VEHICLES = [
  {
    id: 1,
    license_plate: 'KA-01-EQ-9821',
    driver_name: 'Rajesh Kumar',
    driver_rating: 4.9,
    vehicle_model: 'Tata Nexon EV (Electric)',
    status: 'active',
    lat: 12.9716,
    lng: 77.5946,
    speed: 34,
    battery: 88,
    passengers: 2,
    capacity: 4,
  },
  {
    id: 2,
    license_plate: 'KA-05-EV-4410',
    driver_name: 'Priya Sharma',
    driver_rating: 4.85,
    vehicle_model: 'MG ZS EV (Electric)',
    status: 'active',
    lat: 12.965,
    lng: 77.6,
    speed: 28,
    battery: 76,
    passengers: 1,
    capacity: 4,
  },
  {
    id: 3,
    license_plate: 'KA-03-SR-1209',
    driver_name: 'Amit Patel',
    driver_rating: 4.92,
    vehicle_model: 'Hyundai Kona Electric',
    status: 'idle',
    lat: 12.98,
    lng: 77.59,
    speed: 0,
    battery: 95,
    passengers: 0,
    capacity: 4,
  },
  {
    id: 4,
    license_plate: 'KA-02-AI-7788',
    driver_name: 'Sunita Reddy',
    driver_rating: 4.79,
    vehicle_model: 'BYD Atto 3 (EV)',
    status: 'active',
    lat: 12.958,
    lng: 77.612,
    speed: 42,
    battery: 62,
    passengers: 3,
    capacity: 4,
  },
];

export const MOCK_SMART_PICKUP_POINTS = [
  {
    id: 'sp_1',
    name: 'Smart Point A — Indiranagar Metro Gate 2',
    address: '100ft Road, Near Metro Station Exit 2',
    lat: 12.9784,
    lng: 77.6408,
    walkingTime: '2 min walk (120m)',
    safetyScore: 98,
    discountPercent: 15,
    reason: 'AI pickup point: Reduces vehicle detour by 1.8km & saves 6 mins',
  },
  {
    id: 'sp_2',
    name: 'Smart Point B — Koramangala Sony Signal Bay',
    address: '80ft Road, Designated Smart Hub #4',
    lat: 12.9352,
    lng: 77.6245,
    walkingTime: '3 min walk (180m)',
    safetyScore: 96,
    discountPercent: 20,
    reason: 'AI pickup point: Grouping with 2 nearby riders heading to Tech Park',
  },
];

export const MOCK_RIDE_OPTIONS = [
  {
    id: 'opt_smart_pool',
    name: 'Smart AI Pool',
    tagline: 'AI Grouped • Max Savings',
    price: 140,
    originalPrice: 220,
    eta: '6 mins',
    co2SavedKg: '1.4 kg',
    ridersMatched: 2,
    recommended: true,
    badgeText: 'AI RECOMMENDED • 36% OFF',
    icon: 'Users',
  },
  {
    id: 'opt_express_solo',
    name: 'Express Direct EV',
    tagline: 'Zero Emissions • Direct Route',
    price: 210,
    originalPrice: 210,
    eta: '4 mins',
    co2SavedKg: '0.8 kg',
    ridersMatched: 0,
    recommended: false,
    badgeText: 'FLAT FARE',
    icon: 'Zap',
  },
  {
    id: 'opt_premium_exec',
    name: 'Premium EV Sedan',
    tagline: 'Spacious Luxury • AI Smooth Route',
    price: 320,
    originalPrice: 320,
    eta: '5 mins',
    co2SavedKg: '0.9 kg',
    ridersMatched: 0,
    recommended: false,
    badgeText: 'LUXURY EV',
    icon: 'ShieldCheck',
  },
];

export const MOCK_TRIP_HISTORY = [
  {
    id: 'SR-88491',
    date: '10 Aug 2026, 09:15 AM',
    pickup: 'Indiranagar Metro Stn',
    destination: 'Embassy TechVillage, ORR',
    vehicle: 'Tata Nexon EV (KA-01-EQ-9821)',
    driver: 'Rajesh Kumar (4.9★)',
    fare: 140,
    paymentMethod: 'UPI (Google Pay)',
    status: 'completed',
    co2SavedKg: 1.4,
    groupingRiders: 3,
  },
  {
    id: 'SR-88312',
    date: '08 Aug 2026, 06:40 PM',
    pickup: 'Koramangala 5th Block',
    destination: 'MG Road Metro Station',
    vehicle: 'MG ZS EV (KA-05-EV-4410)',
    driver: 'Priya Sharma (4.85★)',
    fare: 125,
    paymentMethod: 'SmartWallet',
    status: 'completed',
    co2SavedKg: 1.2,
    groupingRiders: 2,
  },
  {
    id: 'SR-88105',
    date: '05 Aug 2026, 08:30 AM',
    pickup: 'HSR Layout Sector 1',
    destination: 'Prestige Tech Park',
    vehicle: 'BYD Atto 3 (KA-02-AI-7788)',
    driver: 'Sunita Reddy (4.79★)',
    fare: 160,
    paymentMethod: 'HDFC Credit Card (**** 4912)',
    status: 'completed',
    co2SavedKg: 1.8,
    groupingRiders: 4,
  },
];

export const MOCK_ADMIN_METRICS = {
  totalRides: 48920,
  activeDrivers: 342,
  activeRiders: 1850,
  revenueToday: 184500,
  flatFareSavings: '₹ 4.2 Lakhs saved by riders vs surge pricing',
  co2SavedTotalTons: 142.8,
  avgWaitTimeReductionMinutes: 6.4,
  rideGroupingEfficiencyPercent: 84.6,
};

export const MOCK_DEMAND_HEATMAP_CELLS = [
  { lat: 12.9716, lng: 77.5946, demandScore: 92, zone: 'MG Road CBD', predictedSurgeFactor: 1.0 },
  { lat: 12.9352, lng: 77.6245, demandScore: 88, zone: 'Koramangala Tech Hub', predictedSurgeFactor: 1.0 },
  { lat: 12.9784, lng: 77.6408, demandScore: 78, zone: 'Indiranagar Metro', predictedSurgeFactor: 1.0 },
  { lat: 12.9279, lng: 77.681, demandScore: 96, zone: 'Bellandur / Outer Ring Road', predictedSurgeFactor: 1.0 },
  { lat: 12.99, lng: 77.67, demandScore: 82, zone: 'Whitefield IT Zone', predictedSurgeFactor: 1.0 },
];

export const MOCK_DAILY_ANALYTICS = {
  days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  ridesRequested: [1200, 1350, 1420, 1510, 1890, 2100, 1750],
  aiGroupedRides: [980, 1120, 1210, 1300, 1640, 1820, 1490],
  co2SavedKg: [1370, 1560, 1690, 1820, 2290, 2540, 2080],
};
